--
-- PostgreSQL database dump
--

-- Dumped from database version 13.4 (Ubuntu 13.4-0ubuntu0.21.04.1)
-- Dumped by pg_dump version 13.4 (Ubuntu 13.4-0ubuntu0.21.04.1)

-- Started on 2021-08-14 19:11:46 -03

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO postgres;

--
-- TOC entry 3153 (class 0 OID 0)
-- Dependencies: 3
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 201 (class 1259 OID 18529)
-- Name: comprador; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.comprador (
    id bigint NOT NULL,
    contato character varying(16) NOT NULL,
    cpf character varying(14) NOT NULL,
    nome character varying(255) NOT NULL,
    endereco_id bigint,
    user_id bigint
);


ALTER TABLE public.comprador OWNER TO postgres;

--
-- TOC entry 200 (class 1259 OID 18527)
-- Name: comprador_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.comprador ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comprador_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 203 (class 1259 OID 18536)
-- Name: endereco; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.endereco (
    id bigint NOT NULL,
    bairro character varying(255) NOT NULL,
    cep character varying(255) NOT NULL,
    cidade character varying(255) NOT NULL,
    complemento character varying(255),
    estado character varying(255) NOT NULL,
    numero character varying(255) NOT NULL,
    rua character varying(255) NOT NULL
);


ALTER TABLE public.endereco OWNER TO postgres;

--
-- TOC entry 202 (class 1259 OID 18534)
-- Name: endereco_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.endereco ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.endereco_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 205 (class 1259 OID 18546)
-- Name: funcionario_cecafes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.funcionario_cecafes (
    id bigint NOT NULL,
    cpf character varying(255) NOT NULL,
    matricula character varying(255) NOT NULL,
    nome character varying(255) NOT NULL,
    user_id bigint
);


ALTER TABLE public.funcionario_cecafes OWNER TO postgres;

--
-- TOC entry 204 (class 1259 OID 18544)
-- Name: funcionario_cecafes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.funcionario_cecafes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.funcionario_cecafes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 207 (class 1259 OID 18556)
-- Name: pedido; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pedido (
    id bigint NOT NULL,
    numero character varying(255),
    valor_pedido real,
    comprador_id bigint,
    endereco_id bigint
);


ALTER TABLE public.pedido OWNER TO postgres;

--
-- TOC entry 206 (class 1259 OID 18554)
-- Name: pedido_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pedido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 208 (class 1259 OID 18561)
-- Name: pedido_produto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pedido_produto (
    pedido_id bigint NOT NULL,
    produto_id bigint NOT NULL
);


ALTER TABLE public.pedido_produto OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 18566)
-- Name: produto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.produto (
    id bigint NOT NULL,
    categoria character varying(255),
    data_validade timestamp without time zone NOT NULL,
    foto_url character varying(255),
    nome character varying(255),
    preco character varying(255) NOT NULL,
    quantidade integer NOT NULL,
    unidade_medida character varying(255),
    produtor_id bigint
);


ALTER TABLE public.produto OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 18576)
-- Name: produto_cecafes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.produto_cecafes (
    id bigint NOT NULL,
    categoria character varying(255),
    nome character varying(255),
    preco character varying(255) NOT NULL,
    quantidade integer NOT NULL,
    unidade_medida character varying(255)
);


ALTER TABLE public.produto_cecafes OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 18574)
-- Name: produto_cecafes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.produto_cecafes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produto_cecafes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 18564)
-- Name: produto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.produto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 18586)
-- Name: produto_pedido; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.produto_pedido (
    id bigint NOT NULL,
    categoria character varying(255),
    nome character varying(255),
    preco character varying(255) NOT NULL,
    quantidade integer NOT NULL,
    unidade_medida character varying(255),
    produto_cecafes_id bigint NOT NULL
);


ALTER TABLE public.produto_pedido OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 18584)
-- Name: produto_pedido_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.produto_pedido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produto_pedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 18596)
-- Name: produtor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.produtor (
    id bigint NOT NULL,
    contato character varying(16) NOT NULL,
    cpf character varying(14) NOT NULL,
    nome character varying(255) NOT NULL,
    endereco_id bigint,
    user_id bigint
);


ALTER TABLE public.produtor OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 18594)
-- Name: produtor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.produtor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produtor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 18603)
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    role_id integer NOT NULL,
    name character varying(255)
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 18601)
-- Name: roles_role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 18610)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    enabled boolean NOT NULL,
    password character varying(255),
    username character varying(255)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 18608)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 18618)
-- Name: users_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_roles (
    user_id bigint NOT NULL,
    role_id integer NOT NULL
);


ALTER TABLE public.users_roles OWNER TO postgres;

--
-- TOC entry 3127 (class 0 OID 18529)
-- Dependencies: 201
-- Data for Name: comprador; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.comprador VALUES (1, '(84) 985412365', '854.736.211-20', 'João', 1, 2);


--
-- TOC entry 3129 (class 0 OID 18536)
-- Dependencies: 203
-- Data for Name: endereco; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.endereco VALUES (1, 'taborda', '59842-365', 'natal', NULL, 'RN', '65', 'Rua florida');
INSERT INTO public.endereco VALUES (2, 'Camarão', '59162-000', 'Umarizal', NULL, 'RN', '145', 'Rua do campo');


--
-- TOC entry 3131 (class 0 OID 18546)
-- Dependencies: 205
-- Data for Name: funcionario_cecafes; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.funcionario_cecafes VALUES (1, '988.456.258-78', '56468', 'Fernácio Fagundes', 3);


--
-- TOC entry 3133 (class 0 OID 18556)
-- Dependencies: 207
-- Data for Name: pedido; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.pedido VALUES (1, '852214', 85.43, 1, 1);


--
-- TOC entry 3134 (class 0 OID 18561)
-- Dependencies: 208
-- Data for Name: pedido_produto; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.pedido_produto VALUES (1, 1);


--
-- TOC entry 3136 (class 0 OID 18566)
-- Dependencies: 210
-- Data for Name: produto; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.produto VALUES (1, 'Fruta', '2021-09-14 18:14:57', NULL, 'Maçã', '4,50', 100, 'Quilo', 1);
INSERT INTO public.produto VALUES (2, 'Fruta', '2021-09-15 18:14:57', NULL, 'Banana', '1,50', 500, 'Quilo', 1);
INSERT INTO public.produto VALUES (4, 'Legume', '2021-09-01 18:14:57', NULL, 'Macaxeira', '5,28', 760, 'Quilo', 1);
INSERT INTO public.produto VALUES (5, 'Hortaliça', '2021-08-28 18:14:57', NULL, 'Alface', '2,40', 150, 'Quilo', 1);
INSERT INTO public.produto VALUES (3, 'Verdura', '2021-08-30 18:14:57', NULL, 'Cebola', '4390,00', 2, 'Tonelada', 1);


--
-- TOC entry 3138 (class 0 OID 18576)
-- Dependencies: 212
-- Data for Name: produto_cecafes; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.produto_cecafes VALUES (1, 'Fruta', 'Maçã', '4,50', 400, 'Quilo');
INSERT INTO public.produto_cecafes VALUES (2, 'Fruta', 'Banana', '1,50', 500, 'Quilo');
INSERT INTO public.produto_cecafes VALUES (4, 'Legume', 'Macaxeira', '5,28', 760, 'Quilo');
INSERT INTO public.produto_cecafes VALUES (5, 'Hortaliça', 'Alface', '2,40', 150, 'Quilo');
INSERT INTO public.produto_cecafes VALUES (3, 'Verdura', 'Cebola', '4390,00', 2, 'Tonelada');


--
-- TOC entry 3140 (class 0 OID 18586)
-- Dependencies: 214
-- Data for Name: produto_pedido; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.produto_pedido VALUES (1, 'Fruta', 'Maçã', '4,50', 5, 'Quilo', 1);


--
-- TOC entry 3142 (class 0 OID 18596)
-- Dependencies: 216
-- Data for Name: produtor; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.produtor VALUES (1, '(84) 97745-6213', '987.357.452-98', 'Produtor produtivo', 2, 1);


--
-- TOC entry 3144 (class 0 OID 18603)
-- Dependencies: 218
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.roles VALUES (1, 'PRODUTOR');
INSERT INTO public.roles VALUES (2, 'COMPRADOR');
INSERT INTO public.roles VALUES (3, 'FUNCIONARIO');
INSERT INTO public.roles VALUES (4, 'ADMIN');


--
-- TOC entry 3146 (class 0 OID 18610)
-- Dependencies: 220
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.users VALUES (1, true, '$2a$10$dX8SV.x7DlZZ6aiypG/Kn.gHx0.o5X2E5tiEY3qVw7cYR0mAZlwKy', 'produtor');
INSERT INTO public.users VALUES (2, true, '$2a$10$Ngpq0A0BPUd96iuQ0ApBMuvZWm74GWgd0TOCc3SyhhFXsiTVktrsW', 'comprador');
INSERT INTO public.users VALUES (3, true, '$2a$10$GTxhuOqydE6vG8rZ2xhXpezta93DNpp3xusUXtx162jvoyQIM8GP6', 'funcionario');
INSERT INTO public.users VALUES (4, true, '$2a$10$Lzef7b873kCdqgdCmKN/M.o9jhwAJm6c861eE7Zb/CNXHAg9DwO6i', 'admin');


--
-- TOC entry 3147 (class 0 OID 18618)
-- Dependencies: 221
-- Data for Name: users_roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.users_roles VALUES (1, 1);
INSERT INTO public.users_roles VALUES (2, 2);
INSERT INTO public.users_roles VALUES (3, 3);
INSERT INTO public.users_roles VALUES (4, 4);


--
-- TOC entry 3154 (class 0 OID 0)
-- Dependencies: 200
-- Name: comprador_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.comprador_id_seq', 1, false);


--
-- TOC entry 3155 (class 0 OID 0)
-- Dependencies: 202
-- Name: endereco_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.endereco_id_seq', 1, false);


--
-- TOC entry 3156 (class 0 OID 0)
-- Dependencies: 204
-- Name: funcionario_cecafes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.funcionario_cecafes_id_seq', 1, false);


--
-- TOC entry 3157 (class 0 OID 0)
-- Dependencies: 206
-- Name: pedido_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pedido_id_seq', 1, true);


--
-- TOC entry 3158 (class 0 OID 0)
-- Dependencies: 211
-- Name: produto_cecafes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.produto_cecafes_id_seq', 1, false);


--
-- TOC entry 3159 (class 0 OID 0)
-- Dependencies: 209
-- Name: produto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.produto_id_seq', 1, false);


--
-- TOC entry 3160 (class 0 OID 0)
-- Dependencies: 213
-- Name: produto_pedido_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.produto_pedido_id_seq', 1, false);


--
-- TOC entry 3161 (class 0 OID 0)
-- Dependencies: 215
-- Name: produtor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.produtor_id_seq', 1, false);


--
-- TOC entry 3162 (class 0 OID 0)
-- Dependencies: 217
-- Name: roles_role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_role_id_seq', 1, false);


--
-- TOC entry 3163 (class 0 OID 0)
-- Dependencies: 219
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- TOC entry 2960 (class 2606 OID 18533)
-- Name: comprador comprador_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comprador
    ADD CONSTRAINT comprador_pkey PRIMARY KEY (id);


--
-- TOC entry 2962 (class 2606 OID 18543)
-- Name: endereco endereco_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.endereco
    ADD CONSTRAINT endereco_pkey PRIMARY KEY (id);


--
-- TOC entry 2964 (class 2606 OID 18553)
-- Name: funcionario_cecafes funcionario_cecafes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.funcionario_cecafes
    ADD CONSTRAINT funcionario_cecafes_pkey PRIMARY KEY (id);


--
-- TOC entry 2966 (class 2606 OID 18560)
-- Name: pedido pedido_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedido
    ADD CONSTRAINT pedido_pkey PRIMARY KEY (id);


--
-- TOC entry 2972 (class 2606 OID 18583)
-- Name: produto_cecafes produto_cecafes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produto_cecafes
    ADD CONSTRAINT produto_cecafes_pkey PRIMARY KEY (id);


--
-- TOC entry 2974 (class 2606 OID 18593)
-- Name: produto_pedido produto_pedido_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produto_pedido
    ADD CONSTRAINT produto_pedido_pkey PRIMARY KEY (id);


--
-- TOC entry 2970 (class 2606 OID 18573)
-- Name: produto produto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produto
    ADD CONSTRAINT produto_pkey PRIMARY KEY (id);


--
-- TOC entry 2976 (class 2606 OID 18600)
-- Name: produtor produtor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produtor
    ADD CONSTRAINT produtor_pkey PRIMARY KEY (id);


--
-- TOC entry 2978 (class 2606 OID 18607)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);


--
-- TOC entry 2968 (class 2606 OID 18624)
-- Name: pedido_produto uk_qn57kh961xep0a482lluk5mni; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedido_produto
    ADD CONSTRAINT uk_qn57kh961xep0a482lluk5mni UNIQUE (produto_id);


--
-- TOC entry 2980 (class 2606 OID 18617)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 2982 (class 2606 OID 18622)
-- Name: users_roles users_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT users_roles_pkey PRIMARY KEY (user_id, role_id);


--
-- TOC entry 2993 (class 2606 OID 18675)
-- Name: produtor fk1vcb6i4e0k6lrfn6vtrmvqyav; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produtor
    ADD CONSTRAINT fk1vcb6i4e0k6lrfn6vtrmvqyav FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 2995 (class 2606 OID 18685)
-- Name: users_roles fk2o0jvgh89lemvvo17cbqvdxaa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT fk2o0jvgh89lemvvo17cbqvdxaa FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 2986 (class 2606 OID 18640)
-- Name: pedido fk5uihhvk5ayux0b7iky32iv671; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedido
    ADD CONSTRAINT fk5uihhvk5ayux0b7iky32iv671 FOREIGN KEY (comprador_id) REFERENCES public.comprador(id);


--
-- TOC entry 2991 (class 2606 OID 18665)
-- Name: produto_pedido fk9ay2v1vhmqtnvogr97ofq02s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produto_pedido
    ADD CONSTRAINT fk9ay2v1vhmqtnvogr97ofq02s FOREIGN KEY (produto_cecafes_id) REFERENCES public.produto_cecafes(id);


--
-- TOC entry 2989 (class 2606 OID 18655)
-- Name: pedido_produto fkcsbxw0y9i3wfmiupq9eqfpdtc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedido_produto
    ADD CONSTRAINT fkcsbxw0y9i3wfmiupq9eqfpdtc FOREIGN KEY (pedido_id) REFERENCES public.pedido(id);


--
-- TOC entry 2985 (class 2606 OID 18635)
-- Name: funcionario_cecafes fkdncahgtd4571boyos13qdiyyt; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.funcionario_cecafes
    ADD CONSTRAINT fkdncahgtd4571boyos13qdiyyt FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 2984 (class 2606 OID 18630)
-- Name: comprador fkenjr7aymmlyysgdw0s8auigt5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comprador
    ADD CONSTRAINT fkenjr7aymmlyysgdw0s8auigt5 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 2988 (class 2606 OID 18650)
-- Name: pedido_produto fkf8l3k06bmjhdwd79t0ndcw7tt; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedido_produto
    ADD CONSTRAINT fkf8l3k06bmjhdwd79t0ndcw7tt FOREIGN KEY (produto_id) REFERENCES public.produto(id);


--
-- TOC entry 2990 (class 2606 OID 18660)
-- Name: produto fkftdfs29fqsi5wis7tg2ruecmg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produto
    ADD CONSTRAINT fkftdfs29fqsi5wis7tg2ruecmg FOREIGN KEY (produtor_id) REFERENCES public.produtor(id);


--
-- TOC entry 2992 (class 2606 OID 18670)
-- Name: produtor fkii1odwq7xy0ebfp4m0unknygd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produtor
    ADD CONSTRAINT fkii1odwq7xy0ebfp4m0unknygd FOREIGN KEY (endereco_id) REFERENCES public.endereco(id);


--
-- TOC entry 2994 (class 2606 OID 18680)
-- Name: users_roles fkj6m8fwv7oqv74fcehir1a9ffy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT fkj6m8fwv7oqv74fcehir1a9ffy FOREIGN KEY (role_id) REFERENCES public.roles(role_id);


--
-- TOC entry 2983 (class 2606 OID 18625)
-- Name: comprador fkq9nr7aijm00ip061saxkyv1b8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comprador
    ADD CONSTRAINT fkq9nr7aijm00ip061saxkyv1b8 FOREIGN KEY (endereco_id) REFERENCES public.endereco(id);


--
-- TOC entry 2987 (class 2606 OID 18645)
-- Name: pedido fksot2og0lvhm2t4kuu9s2obef3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedido
    ADD CONSTRAINT fksot2og0lvhm2t4kuu9s2obef3 FOREIGN KEY (endereco_id) REFERENCES public.endereco(id);


-- Completed on 2021-08-14 19:11:46 -03

--
-- PostgreSQL database dump complete
--

